"use strict";
(function(){
var W=window.registrarPalavraSimples||function(){};
var w=function(p,c,d){W(p,c,d);};
w("formiga","Animais",["Inseto pequeno","Vive em colonias","Carrega folhas","Muito trabalhadora","Preta ou vermelha"]);
w("tartaruga","Animais",["Casco duro","Anda devagar","Vive muito tempo","Verde","Marinha ou terrestre"]);
w("tubarao","Animais",["Predador marinho","Dentes afiados","Barbatana","Maior peixe","Tem medo"]);
w("golfinho","Animais",["Inteligente","Mamifero marinho","Saltos","Amigavel","Treinado"]);
w("arara","Animais",["Colorida","Bico curvo","Mata atlantica","Verde e azul","Voa alto"]);
w("coruja","Animais",["Noturna","Sabia","Enxerga no escuro","Gira a cabeca","Pia"]);
w("rato","Animais",["Pequeno","Gosta de queijo","Fugitivo","Mamifero","Roe"]);
w("sapo","Animais",["Pula","Come insetos","Verde","Olhos grandes","Vive perto dagua"]);
w("lagartixa","Animais",["Parede","Pequena","Rasteja","Rapida","Muda de cor"]);
w("camelo","Animais",["Deserto","Corcova","Armazena agua","Longas caminhadas","Resistente"]);
w("zebra","Animais",["Listras","Africa","Parecido com cavalo","Preto e branco","Manada"]);
w("rinoceronte","Animais",["Grande","Chifre","Couro grosso","Pesado","Perigoso"]);
w("hipopotamo","Animais",["Rio","Grande","Boca enorme","Agua","Pesado"]);
w("caracol","Animais",["Concha","Devagar","Rastro","Antenas","Molusco"]);
w("minhoca","Animais",["Cavouca","Fina","Comprida","Terra","Sem ossos"]);
w("esquilo","Animais",["Arvores","Nozes","Rapido","Cauda peluda","Pequeno"]);
w("pavao","Animais",["Cauda colorida","Linda","Abre leque","Azul e verde","Dancarino"]);
w("periquito","Animais",["Verde","Pequeno","Gaiola","Fala","Voar"]);
w("beija-flor","Animais",["Voar parado","Bico comprido","Flor","Nectar","Asas rapidas"]);
w("polvo","Animais",["Oito tentaculos","Inteligente","Marinho","Tinta","Mole"]);
w("caranguejo","Animais",["Pincas","Anda de lado","Praia","Marinho","Casquinha"]);
w("lagosta","Animais",["Marinho","Pincas","Delicosa","Vermelha","Antenas"]);
w("cervo","Animais",["Chifres","Mata","Rapido","Mamifero","Galhada"]);
w("lobo","Animais",["Matilha","Uiva","Selvagem","Cinza","Predador"]);
w("raposa","Animais",["Esperta","Laranja","Cauda peluda","Sorrateira","Mamifero"]);
w("tigre","Animais",["Listras","Felino","Selvagem","Laranja e preto","Grande"]);
w("panda","Animais",["Comer bambu","Preto e branco","China","Urso","Pacfico"]);
w("canguru","Animais",["Bolsa","Pula","Australia","Mamifero","Filhote na bolsa"]);
w("jacare","Animais",["Dentes","Rio","Escamas","Perigoso","Morde forte"]);
w("camaleao","Animais",["Muda de cor","Lingua longa","Rasteja","Insetos","Olhos que rodam"]);
w("vagalume","Animais",["Brilha","Luz propria","Noturno","Inseto","Verde amarelado"]);
w("aranha","Animais",["Teia","Oito patas","Insetos","Tarantula","Fio de seda"]);
w("escorpiao","Animais",["Ferrao","Perigoso","Caverna","Oito patas","Veneno"]);
w("lesma","Animais",["Molusco","Lento","Rastro","Chuva","Mole"]);
w("cavalo-marinho","Animais",["Pequeno","Cauda enrolada","Marinho","Macho gestante","Curioso"]);
w("ourico","Animais",["Espinhos","Bola","Mamifero","Pequeno","Defesa"]);
w("toupeira","Animais",["Tuneis","Cega","Terra","Focinho","Mamifero"]);
w("morcego","Animais",["Voa","Noturno","Ecolocalizacao","Caverna","Asas"]);
w("foca","Animais",["Marinho","Bolas","Gorda","Bigodes","Treinada"]);
w("morsa","Animais",["Presas","Gelada","Grande","Marinho","Bigodes"]);
w("javali","Animais",["Selvagem","Presas","Floresta","Peludo","Parece porco"]);
w("pomba","Animais",["Paz","Branca","Voa","Urbana","ArruIho"]);
w("cisne","Animais",["Branco","Pescoco longo","Lago","Elegante","Casal"]);
w("peru","Animais",["Gordo","Natal","Poupa","Colorido","Glu-glu"]);
w("avestruz","Animais",["Grande","Nao voa","Corre","Pescoco comprido","Africano"]);
w("ema","Animais",["Nao voa","Corre","Brasileira","Grande","Cerrado"]);
w("pulga","Animais",["Pula alto","Pequena","Cachorro","Picada","Incomoda"]);
w("barata","Animais",["Antenas","Preta","Cozinha","Rapida","Inseto"]);
w("gafanhoto","Animais",["Pula","Verde","Asas","Antenas","Campo"]);
w("joaninha","Animais",["Pequena","Vermelha","Pontos pretos","Jardim","Inseto"]);
w("bruxa","Fantasia",["Vassoura","Chapeu pontudo","Caldeirao","Voce","Magia"]);
w("fada","Fantasia",["Asas","Magia","Pequena","Varinhna","Luz"]);
w("unicornio","Fantasia",["Chifre","Branco","Magico","Cavalo","Arco-iris"]);
w("dragao","Fantasia",["Fogo","Asas","Escamas","Grande","Voa"]);
w("sereia","Fantasia",["Cauda de peixe","Mar","Canta","Bela","Raposa do mar"]);
w("elfo","Fantasia",["Orelhas","Arqueiro","Floresta","Magico","Imortal"]);
w("arco-iris","Natureza",["Cores","Apos chuva","Sol","Arco","Colorido"]);
w("terremoto","Natureza",["Tremor","Terra","Destruicao","Abalo","Perigo"]);
w("vulcao","Natureza",["Fogo","Lava","Montanha","Erupcao","Magma"]);
w("deserto","Natureza",["Areia","Calor","Camelo","Oasis","Grande"]);
w("cachoeira","Natureza",["Agua","Altura","Linda","Som","Natureza"]);
w("lago","Natureza",["Agua","Parado","Peixes","Reflexo","Calmo"]);
w("mar","Natureza",["Agua salgada","Ondas","Praia","Grande","Profundo"]);
w("nuvem","Natureza",["Branca","Alto","Chuva","Fofa","Ceular"]);
w("vento","Natureza",["Sopra","Forte","Fresco","Invisivel","Move"]);
w("relampago","Natureza",["Luz","Tempestade","Ceular","Rapido","Eletrico"]);
w("neblina","Natureza",["Branca","Fria","Visibilidade","Manha","Nevoa"]);
w("eclipse","Natureza",["Sol","Lua","Escuro","Raro","Alinhamento"]);
w("recife","Natureza",["Coral","Marinho","Peixes","Colorido","Ecossistema"]);
w("gruta","Natureza",["Caverna","Pedra","Escura","Natural","Fria"]);
w("pantano","Natureza",["Agua","Lama","Jacare","Arvores","Perigo"]);
w("cerrado","Natureza",["Brasil","Arvores tortas","Savana","Bioma","Seco"]);
w("amazonia","Natureza",["Maior floresta","Brasil","Rio","Bioma","Verde"]);
w("caverna","Natureza",["Escura","Pedra","Estalactite","Fria","Profunda"]);
w("ilha","Natureza",["Mar","Areia","Sozinha","Palmeira","Remota"]);
w("abacate","Comidas",["Verde","Cremoso","Vitaminas","Guacamole","Fruta"]);
w("abacaxi","Comidas",["Doce","Acido","Coroa","Tropical","Amarelo"]);
w("acerola","Comidas",["Vitamina C","Vermelha","Pequena","Acida","Fruta"]);
w("amora","Comidas",["Roxa","Doce","Pequena","Fruta","Selvagem"]);
w("caju","Comidas",["Castanha","Pseudofruto","Nordeste","Acido","Tropical"]);
w("cereja","Comidas",["Vermelha","Doce","Pequena","Fruta","Bolo"]);
w("coco","Comidas",["Agua","Fibra","Marrom","Branca","Tropical"]);
w("figo","Comidas",["Doce","Fruta","Roxo","Mediterraneo","Mole"]);
w("goiaba","Comidas",["Verde","Vermelha","Doce","Vitamina C","Fruta"]);
w("jaca","Comidas",["Grande","Cheirosa","Nordeste","Fruta","Pesada"]);
w("kiwi","Comidas",["Verde","Pequeno","Peludo","Acido","Vitamina C"]);
w("limao","Comidas",["Acido","Verde","Vitamina C","Tropical","Azedo"]);
w("mamao","Comidas",["Laranja","Doce","Manha","Digestivo","Fruta"]);
w("manga","Comidas",["Amarela","Doce","Tropical","Suco","Fruta"]);
w("melancia","Comidas",["Vermelha","Refrescante","Grande","Verde","Agua"]);
w("morango","Comidas",["Vermelho","Doce","Frutas","Sorvete","Coracao"]);
w("pera","Comidas",["Verde","Doce","Macia","Fruta","Formato"]);
w("pesego","Comidas",["Laranja","Peludo","Doce","Suco","Delicia"]);
w("uva","Comidas",["Roxa","Pequena","Vinho","Cacho","Doce"]);
w("ameixa","Comidas",["Roxa","Doce","Caroco","Fruta","Macia"]);
w("framboesa","Comidas",["Vermelha","Pequena","Doce","Selvagem","Torta"]);
w("pitanga","Comidas",["Vermelha","Arvore","Acida","Brasileira","Jardim"]);
w("pao","Comidas",["Farinha","Forno","Massa","Cafe da manha","Trigo"]);
w("queijo","Comidas",["Leite","Amarelo","Derretido","Massa","Minas"]);
w("presunto","Comidas",["Carne","Fatiado","Sanduiche","Defumado","Salgado"]);
w("ovo","Comidas",["Galinha","Frito","Cozido","Omelete","Proteina"]);
w("leite","Comidas",["Branco","Vaca","Bebida","Calcio","Creme"]);
w("arroz","Comidas",["Grao","Branco","Feijao","Brasileiro","Quentinha"]);
w("feijao","Comidas",["Preto","Carioquinha","Tropeiro","Mineiro","Brasileiro"]);
w("batata","Comidas",["Frita","Cozida","Marrom","Mandioca","Inglesa"]);
w("cebola","Comidas",["Choro","Roxa","Branca","Tempero","Casca"]);
w("alho","Comidas",["Tempero","Branco","Pequeno","Cheiroso","Bulbo"]);
w("cenoura","Comidas",["Laranja","Coelho","Vitamina","Legume","Crua"]);
w("alface","Comidas",["Verde","Salada","Folhas","Fresca","Crua"]);
w("tomate","Comidas",["Vermelho","Molho","Salada","Fruta","Salada"]);
w("milho","Comidas",["Amarelo","Pamonha","Curral","Espiga","Doce"]);
w("ervilha","Comidas",["Verde","Pequena","Legume","Enlatada","Doce"]);
w("beterraba","Comidas",["Roxa","Salada","Doce","Legume","Terra"]);
w("chocolate","Comidas",["Doce","Cacau","Amargo","Ao leite","Branco"]);
w("chiclete","Comidas",["Mascar","Bolinha","Sabores","Bola","Bubble"]);
w("pipoca","Comidas",["Cinema","Milho","Estourada","Salgada","Doce"]);
w("pao-de-queijo","Comidas",["Mineiro","Queijo","Polvilho","Bolinha","Assado"]);
w("acucar","Comidas",["Doce","Branco","Cristal","Refinado","Cafe"]);
w("sal","Comidas",["Branco","Tempero","Marinho","Mesa","Salgado"]);
w("agua","Bebidas",["Limpa","Vida","Gelada","Sem cor","Fonte"]);
w("refrigerante","Bebidas",["Gas","Doce","Cola","Gelado","Lata"]);
w("suco","Bebidas",["Natural","Laranja","Vitaminas","Gelado","Copo"]);
w("cha","Bebidas",["Quente","Ervas","Xicara","Relaxante","Frio"]);
w("cerveja","Bebidas",["Cevada","Gelada","Chopp","Latinha","Amarga"]);
w("vinho","Bebidas",["Uva","Tinto","Branco","Taca","Seco"]);
w("cachaca","Bebidas",["Cana-de-acucar","Brasileira","Caipirinha","Destilada","Forte"]);
w("energetico","Bebidas",["Cafeina","Gas","Lata","Disposicao","Vermelho"]);
w("advogado","Profissoes",["Tribunal","Leis","Processos","Justica","Tribunal"]);
w("dentista","Profissoes",["Dentes","Sorriso","Boca","Anestesia","Canal"]);
w("engenheiro","Profissoes",["Obras","Calculos","Projetos","Construcao","Estruturas"]);
w("arquiteto","Profissoes",["Projetos","Casas","Plantas","Design","Criativo"]);
w("jornalista","Profissoes",["Noticias","Reportagem","Entrevista","Imprensa","Texto"]);
w("fotografo","Profissoes",["Camera","Fotos","Imagens","Luz","Instantaneo"]);
w("musico","Profissoes",["Instrumento","Notas","Palco","Bandas","Melodia"]);
w("cantor","Profissoes",["Musica","Voz","Palco","Show","Melodia"]);
w("escritor","Profissoes",["Livros","Historias","Palavras","Autor","Romance"]);
w("astronauta","Profissoes",["Espaco","Foguete","Gravidade","Lua","Nave"]);
w("juiz","Profissoes",["Justica","Tribunal","Sentenca","Leis","Toga"]);
w("piloto","Profissoes",["Aviao","Voo","Comandante","Ceular","Uniforme"]);
w("mecanico","Profissoes",["Carros","Oficina","Ferramentas","Motor","Conserto"]);
w("eletricista","Profissoes",["Fios","Luz","Tomada","Instalacao","Choque"]);
w("encanador","Profissoes",["Agua","Cano","Vazamento","Pia","Conserto"]);
w("carpinteiro","Profissoes",["Madeira","Moveis","Martelo","Serrote","Oficina"]);
w("padeiro","Profissoes",["Pao","Forno","Farinha","Massa","Cafe"]);
w("agricultor","Profissoes",["Terra","Plantacao","Colheita","Trator","Campo"]);
w("pescador","Profissoes",["Peixe","Anzol","Rede","Mar","Barco"]);
w("veterinario","Profissoes",["Animais","Clinica","Cuidados","Saude","Pet"]);
w("psicologo","Profissoes",["Mente","Terapia","Conversa","Ajuda","Emocoes"]);
w("farmaceutico","Profissoes",["Remedios","Farmacia","Receita","Comprimidos","Saude"]);
w("programador","Profissoes",["Computador","Codigo","Software","Teclado","Tela"]);
w("designer","Profissoes",["Criatividade","Arte","Digital","Projetos","Cores"]);
w("chef","Profissoes",["Cozinha","Receitas","Sabor","Restaurante","Facao"]);
w("garcom","Profissoes",["Mesa","Restaurante","Pedidos","Bandeja","Atendimento"]);
w("zelador","Profissoes",["Limpeza","Predio","Cuidados","Vassoura","Organizacao"]);
w("seguranca","Profissoes",["Protecao","Vigilancia","Uniforme","Portaria","Ronda"]);
w("motorista","Profissoes",["Dirige","Volante","Carro","Transporte","Viajem"]);
w("professor","Profissoes",["Ensina","Escola","Quadro","Alunos","Educacao"]);
w("medico","Profissoes",["Cuida da saude","Hospital","Receita","Estetoscopio","Clinico"]);
w("bombeiro","Profissoes",["Apaga fogo","Resgata","Caminhao vermelho","Emergencia","Mangueira"]);
w("policial","Profissoes",["Seguranca","Protege","Farda","Viatura","Patrulha"]);
w("cozinheiro","Profissoes",["Cozinha","Prepara comida","Restaurante","Chef","Panelas"]);
w("pedreiro","Profissoes",["Constroi","Tijolos","Obra","Construcao civil","Cimento"]);
w("celular","Tecnologia",["Aparelho","Touch","Aplicativos","Chamadas","Moderno"]);
w("tablet","Tecnologia",["Tela grande","Touch","Portatil","Digital","Leitura"]);
w("notebook","Tecnologia",["Portatil","Teclado","Tela","Trabalho","Estudo"]);
w("impressora","Tecnologia",["Papel","Tinta","Documentos","Digital","Scanner"]);
w("mouse","Tecnologia",["Clique","Cursor","Movimento","Cabo","Wireless"]);
w("teclado","Tecnologia",["Digitar","Teclas","Computador","Letras","Numeros"]);
w("monitor","Tecnologia",["Tela","Computador","Video","Imagem","Display"]);
w("fone","Tecnologia",["Audio","Ouvido","Musica","Chamadas","Conforto"]);
w("carregador","Tecnologia",["Tomada","Bateria","Cabo","Energia","Recarga"]);
w("roteador","Tecnologia",["Internet","Wifi","Sinal","Rede","Conexao"]);
w("camera","Tecnologia",["Foto","Video","Lente","Imagem","Flash"]);
w("drone","Tecnologia",["Voa","Camera","Controle","Filmagem","Altura"]);
w("robo","Tecnologia",["Mecanico","Autonomo","Programa","Movimento","Inteligente"]);
w("pendrive","Tecnologia",["USB","Armazenamento","Dados","Portatil","Arquivos"]);
w("televisao","Tecnologia",["Tela","Programas","Canais","Novela","Filme"]);
w("radio","Tecnologia",["FM","AM","Musica","Noticias","Antena"]);
w("video-game","Tecnologia",["Jogos","Controle","Console","Diversao","Tela"]);
w("surfe","Esportes",["Onda","Prancha","Mar","Equilibrio","Praia"]);
w("skate","Esportes",["Rodas","Pista","Manobra","Rampa","Shape"]);
w("capoeira","Esportes",["Brasileira","Danca","Luta","Berimbau","Ginga"]);
w("boxe","Esportes",["Luvas","Ringue","Nocaute","Soco","Luta"]);
w("judo","Esportes",["Kimono","Faixa","Luta","Japao","Queda"]);
w("esgrima","Esportes",["Espada","Mascara","Combate","Agilidade","Pontos"]);
w("golfe","Esportes",["Buraco","Taco","Bola","Campo verde","Precisao"]);
w("mergulho","Esportes",["Agua","Profundo","Cilindro","Mar","Snorkel"]);
w("paraquedismo","Esportes",["Altura","Queda","Ceular","Aventura","Paraquedas"]);
w("canoagem","Esportes",["Canoa","Rio","Remo","Agua","Aventura"]);
w("escalada","Esportes",["Montanha","Corda","Agarrar","Altura","Equipamento"]);
w("ioga","Esportes",["Postura","Respirao","Flexibilidade","Meditao","Relaxamento"]);
w("trilha","Esportes",["Caminhada","Montanha","Natureza","Rota","Aventura"]);
w("ambulancia","Transportes",["Emergencia","Saude","Hospital","Sirene","Socorro"]);
w("trator","Transportes",["Fazenda","Agricultura","Roca","Grande","Lento"]);
w("patinete","Transportes",["Infantil","Duas rodas","Empurrar","Pe no chao","Dobravel"]);
w("jetski","Transportes",["Agua","Motor","Rapido","Mar","Esporte"]);
w("submarino","Transportes",["Agua","Profundo","Marinho","Militar","Janelas"]);
w("teleferico","Transportes",["Cabos","Altitude","Bonde","Montanha","Turismo"]);
w("metro","Transportes",["Trem","Subterraneo","Rapido","Urbano","Estacao"]);
w("caminhonete","Transportes",["Utilitaria","Cacamba","Pickup","Grande","Carga"]);
w("helicoptero","Transportes",["Voa","Helices em cima","Paira no ar","Resgates","Rotores"]);
w("onibus","Transportes",["Transporta pessoas","Anda nas ruas","Bancos","Passagem","Coletivo"]);
w("cavalo","Transportes ja registrado",["Animais","Galopa","Montaria","Crina","Sela"]);
w("bicicleta ja registrada","Transportes ja registrado",["Duas rodas","Pedal","Nao polui","Veiculo"]);
w("futebol","Lazer ja registrado",["Esporte popular","Gol","Bola","Jogadores","Campo"]);
w("basquete","Esportes",["Cesta","Quadra","5 jogadores","Arremesso","Pontos"]);
w("natacao","Esportes",["Nadar","Piscina","Agua","Medalhas","Estilo"]);
w("tenis","Esportes",["Raquete","Bola","Quadra","Dois jogadores","Saques"]);
w("volei","Esportes",["Rede","Saque","6 jogadores","Toque","Bloqueio"]);
w("ciclismo","Esportes",["Bicicleta","Pedalar","Capacete","Estrada","Velocidade"]);
w("aeroporto","Lugares",["Aviao","Viagem","Pista","Terminal","Embarque"]);
w("castelo","Lugares",["Rei","Torre","Antigo","Muralha","Medieval"]);
w("museu","Lugares",["Arte","Historia","Exposicao","Visita","Quadros"]);
w("teatro","Lugares",["Palco","Apresentacao","Plateia","Cortina","Atuacao"]);
w("cinema","Lugares",["Filme","Tela","Poltrona","Pipoca","Sessao"]);
w("parque","Lugares",["Verde","Ar livre","Brincar","Passeio","Grama"]);
w("jardim","Lugares",["Flores","Plantas","Natureza","Cuidado","Colorido"]);
w("estadio","Lugares",["Esporte","Torcida","Campo","Arquibancada","Jogo"]);
w("academia","Lugares",["Exercicio","Musculos","Pesos","Treino","Saude"]);
w("zoologico","Lugares",["Animais","Gaiolas","Visita","Selvagens","Educacao"]);
w("laboratorio","Lugares",["Ciencia","Experimentos","Pesquisa","Bancada","Microscopio"]);
w("fabrica","Lugares",["Producao","Maquinas","Operarios","Produtos","Industria"]);
w("fazenda","Lugares",["Campo","Animais","Plantacao","Sitio","Colheita"]);
w("hotel","Lugares",["Quarto","Viagem","Hospedagem","Reserva","Conforto"]);
w("floresta","Lugares",["Arvores","Animais","Natureza","Sombra","Densa"]);
w("ponte","Lugares",["Rio","Passagem","Conexao","Ligacao","Pedra"]);
w("cidade","Lugares",["Grande","Urbano","Movimento","Predios","Capital"]);
w("vila","Lugares",["Pequena","Interior","Pacata","Comunidade","Campo"]);
w("praia","Lugares ja registrada",["Mar","Areia","Sol","Verao","Ondas"]);
w("escola","Lugares ja registrada",["Estudar","Sala de aula","Professor","Educacao","Alunos"]);
w("hospital","Lugares ja registrada",["Saude","Medicos","Doentes","Emergencia","Cura"]);
w("igreja","Lugares ja registrada",["Religiao","Oracao","Fe","Deus","Frequentar"]);
w("olho","Corpo",["Visao","Ver","Orbita","Iris","Pupila"]);
w("nariz","Corpo",["Olfato","Cheiro","Respirao","Rosto","Fossas"]);
w("boca","Corpo",["Fala","Comer","Labios","Dentes","Sorriso"]);
w("orelha","Corpo",["Audicao","Ouvido","Som","Lobulo","Fone"]);
w("cabelo","Corpo",["Cabeca","Fios","Pente","Corte","Look"]);
w("mao","Corpo",["Dedos","Tocar","Pegar","Palma","Unhas"]);
w("pe","Corpo",["Andar","Sapato","Dedos","Calcanhar","Pisar"]);
w("coracao","Corpo ja registrado",["Bombeia","Sangue","Batimentos","Amor","Vida"]);
w("cerebro","Corpo",["Pensar","Mente","Nos","Inteligencia","Memoria"]);
w("pulmao","Corpo",["Respirar","Ar","Oxigenio","Peito","Inspirar"]);
w("estomago","Corpo",["Digestao","Comida","Acido","Fome","Barriga"]);
w("osso","Corpo",["Estrutura","Esqueleto","Forte","Corpo","Calcio"]);
w("pele","Corpo",["Corpo","Tato","Maior orgao","Protecao","Toque"]);
w("sangue","Corpo",["Vermelho","Veias","Vida","Circulacao","Coracao"]);
w("camiseta","Vestuario",["Roupa","Algodao","Curta","Colorida","Dia a dia"]);
w("calca","Vestuario",["Perna","Comprida","Jeans","Algodao","Social"]);
w("vestido","Vestuario",["Feminino","Saia","Roupa","Festa","Leve"]);
w("saia","Vestuario",["Feminina","Roda","Roupa","Curta","Comprida"]);
w("terno","Vestuario",["Social","Paleto","Gravata","Executivo","Elegante"]);
w("casaco","Vestuario",["Frio","Abrigo","Inverno","Ziper","Agasalho"]);
w("biquini","Vestuario",["Praia","Piscina","Feminino","Verao","Duas pecas"]);
w("cachecol","Vestuario",["Pescoco","Frio","Inverno","La","Quente"]);
w("luva","Vestuario",["Maos","Frio","Inverno","Protecao","Dedos"]);
w("bone","Vestuario",["Cabeca","Sol","Aba","Esporte","Bone"]);
w("pijama","Vestuario",["Dormir","Conforto","Noite","Algodao","Quarto"]);
w("mochila","Vestuario",["Costas","Carregar","Escola","Viagem","Bolsa"]);
w("oculos-sol","Vestuario",["Sol","Lentes","Protecao","Moda","Visual"]);
w("oculos","Vestuario ja registrado",["Enxergar","Lentes","Grau","Rosto","Armacao"]);
w("relogio-pulso","Vestuario",["Horas","Pulso","Acessorio","Marca","Tempo"]);
w("pulseira","Vestuario",["Pulso","Acessorio","Enfeite","Moda","Colorida"]);
w("colar","Vestuario",["Pescoco","Acessorio","Joia","Brilho","Corrente"]);
w("brinco","Vestuario",["Orelha","Acessorio","Joia","Feminino","Argola"]);
w("anel","Vestuario",["Dedo","Joia","Casamento","Compromisso","Ouro"]);
w("piano","Instrumentos",["Teclas","Branco e preto","Musica","Classico","Som"]);
w("violao","Instrumentos",["Cordas","Acustico","Samba","Musica","Tocar"]);
w("bateria","Instrumentos",["Tambores","Baqueta","Ritmo","Percussao","Musica"]);
w("flauta","Instrumentos",["Sopro","Doce","Tubos","Notas","Musica"]);
w("saxofone","Instrumentos",["Sopro","Jazz","Metal","Palheta","Som"]);
w("trompete","Instrumentos",["Sopro","Metal","Jazz","Fanfarra","Som"]);
w("violino","Instrumentos",["Cordas","Arco","Classico","Som agudo","Orquestra"]);
w("harpa","Instrumentos",["Cordas","Grande","Angular","Classico","Dedilhado"]);
w("acordeon","Instrumentos",["Fole","Botoes","Sopro","Popular","Forro"]);
w("sanfona","Instrumentos",["Fole","Nordestina","Forro","Puxa","Musica"]);
w("gaita","Instrumentos",["Pequena","Sopro","Boca","Notas","Blues"]);
w("tambor","Instrumentos",["Pele","Baqueta","Ritmo","Indigena","Percussao"]);
w("pandeiro","Instrumentos",["Pele","Soalhas","Samba","Ritmo","Brasileiro"]);
w("berimbau","Instrumentos",["Capoeira","Corda","Cabaca","Baqueta","Brasileiro"]);
w("cuica","Instrumentos",["Som engraado","Brasileira","Percussao","Friccao","Samba"]);
w("sino","Instrumentos",["Metal","Som","Igreja","Torre","Badaladas"]);
w("apito","Instrumentos",["Sopro","Agudo","Juiz","Treinador","Som"]);
w("alegria","Sentimentos",["Feliz","Sorriso","Bom","Positivo","Energia"]);
w("tristeza","Sentimentos",["Choro","Desanimo","Sozinho","Magoado","Saudade"]);
w("amor","Sentimentos",["Carinho","Afeto","Coracao","Paixao","Querer bem"]);
w("medo","Sentimentos",["Susto","Perigo","Assustado","Temor","Inseguranca"]);
w("raiva","Sentimentos",["Irritado","Bravo","Nervoso","Estressado","Furia"]);
w("surpresa","Sentimentos",["Susto","Novidade","Admirado","Uau","Espanto"]);
w("vergonha","Sentimentos",["Timidez","Corar","Inibicao","Acanhamento","Constrangimento"]);
w("gratidao","Sentimentos",["Obrigado","Reconhecimento","Agradecimento","Valorizacao","Bencao"]);
w("esperanca","Sentimentos",["Acreditar","Fe","Otimismo","Futuro","Positivo"]);
w("saudade","Sentimentos",["Falta","Nostalgia","Lembranca","Distancia","Querer ver"]);
w("calma","Sentimentos",["Paz","Tranquilidade","Serenidade","Relaxamento","Descanso"]);
w("coragem","Sentimentos",["Forca","Valentia","Destemor","Atitude","Superacao"]);
w("amizade","Sentimentos",["Amigo","Lealdade","Parceiro","Confianca","Uniao"]);
w("paixao","Sentimentos",["Amor forte","Desejo","Intenso","Coracao","Fogo"]);
w("felicidade","Sentimentos",["Alegria","Contentamento","Prazer","Bem-estar","Sorriso"]);
w("correr","Acoes",["Movimento","Rapido","Passos","Atleta","Velocidade"]);
w("pular","Acoes",["Salto","Altura","Movimento","Suspeno","Impulso"]);
w("cantar","Acoes",["Musica","Voz","Melodia","Cancao","Tom"]);
w("dancar","Acoes",["Ritmo","Movimento","Musica","Passos","Coreografia"]);
w("comer","Acoes",["Alimento","Mastigar","Refeicao","Nutricao","Fome"]);
w("beber","Acoes",["Agua","Sede","Liquido","Copo","Ingerir"]);
w("dormir","Acoes",["Cama","Sono","Descansar","Sonho","Noite"]);
w("ler","Acoes",["Livro","Palavras","Historia","Conhecimento","Paginas"]);
w("escrever","Acoes",["Papel","Lapis","Letras","Texto","Caneta"]);
w("desenhar","Acoes",["Lapis","Papel","Criatividade","Arte","Tracos"]);
w("pintar","Acoes",["Tinta","Pincel","Tela","Cor","Arte"]);
w("cozinhar","Acoes",["Fogao","Comida","Panela","Receita","Fogo"]);
w("limpar","Acoes",["Organizar","Vassoura","Pano","Limpeza","Casa"]);
w("jogar","Acoes",["Bola","Brincar","Divertir","Esporte","Partida"]);
w("nadar","Acoes",["Agua","Piscina","Natacao","Movimento","Mar"]);
w("caminhar","Acoes",["Passos","Passeio","Movimento","Devagar","Ar livre"]);
w("abraar","Acoes",["Carinho","Amor","Aconchego","Bracos","Apertar"]);
w("sorrir","Acoes",["Alegria","Boca","Feliz","Dentes","Contentamento"]);
w("chorar","Acoes",["Tristeza","Lagrimas","Olhos","Emocao","Sentimento"]);
w("subir","Acoes",["Escada","Altura","Elevacao","Cima","Montanha"]);
w("descer","Acoes",["Escada","Abaixo","Movimento","Altura","Reducao"]);
w("sentar","Acoes",["Cadeira","Descansar","Posicao","Assento","Conforto"]);
w("cadeira","Objetos ja registrado",["Sentar","Pernas","Encosto","Casa","Moveis"]);
w("mesa","Objetos ja registrado",["Refeicoes","Tampo","Pernas","Cozinha","Comida"]);
w("cama","Objetos ja registrado",["Dormir","Colchao","Travesseiro","Quarto","Conforto"]);
w("copo","Objetos ja registrado",["Beber agua","Cilindrico","Transparente","Vidro","Liquido"]);
w("chapeu","Objetos ja registrado",["Cabeca","Protege do sol","Aba","Moda","Usar"]);
w("sapato","Objetos ja registrado",["Calcado","Protege os pes","Cadaco","Dia a dia","Vestir"]);
w("martelo","Objetos ja registrado",["Ferramenta","Bater","Prego","Construcao","Obra"]);
w("tesoura","Objetos ja registrado",["Corte","Duas laminas","Corta papel","Argolas","Maos"]);
w("guitarra","Objetos ja registrado",["Instrumento","Cordas","Rock","Corpo","Bracos"]);
w("lanterna","Objetos",["Luz","Escuro","Pilha","Iluminar","Maos"]);
w("vela","Objetos",["Fogo","Luz","Cera","Pavio","Escuro"]);
w("vaso","Objetos",["Planta","Flores","Ceramica","Decorar","Terra"]);
w("prato","Objetos",["Comer","Refeicao","Mesa","Redondo","Louca"]);
w("xicara","Objetos",["Cafe","Cha","Pequena","Alca","Bebida"]);
w("garfo","Objetos",["Talher","Dentes","Comer","Mesa","Metal"]);
w("faca","Objetos",["Cortar","Lmina","Mesa","Cozinha","Afiada"]);
w("colher","Objetos",["Talher","Sopa","Comer","Mesa","Concava"]);
w("panela","Objetos",["Cozinhar","Fogao","Alimento","Metal","Tampa"]);
w("geladeira","Objetos",["Frio","Alimentos","Cozinha","Conservar","Eletrica"]);
w("fogao","Objetos",["Cozinhar","Fogo","Cozinha","Bocas","Forno"]);
w("guarda-chuva","Objetos",["Chuva","Protecao","Abrir","Molhado","Ceular"]);
w("vassoura","Objetos",["Limpeza","Chao","Cerdas","Cabo","Varrer"]);
w("lixeira","Objetos",["Lixo","Cesto","Jogar fora","Descarte","Sujo"]);
w("pente","Objetos",["Cabelo","Desembaracar","Plastico","Higiene","Dentes"]);
w("toalha","Objetos",["Banho","Enxugar","Tecido","Corpo","Felpa"]);
w("travesseiro","Objetos",["Cabeca","Dormir","Macio","Conforto","Cama"]);
w("cobertor","Objetos",["Frio","Cama","Aquecer","Manta","Quente"]);
w("tapete","Objetos",["Chao","Decorar","Sala","Quarto","Felpa"]);
w("cortina","Objetos",["Janela","Sol","Privacidade","Tecido","Sala"]);
w("lampada","Objetos",["Luz","Clara","LED","Incandescente","Iluminar"]);
w("pilha","Objetos",["Cilindro","Energia","Portatil","Brinquedo","Remoto"]);
w("bussola","Objetos",["Norte","Direcao","Magnetico","Agulha","Orientar"]);
w("caixa","Objetos",["Papelao","Guardar","Embalagem","Cubo","Presente"]);
w("balde","Objetos",["Agua","Plastico","Alca","Limpeza","Cilindrico"]);
w("espelho","Objetos",["Reflexo","Rosto","Parede","Vidro","Olhar"]);
w("mala","Objetos",["Viagem","Roupas","Transportar","Rodas","Alca"]);
w("caneta","Objetos",["Escrever","Tinta","Azul","Preta","Papel"]);
w("lapis","Objetos",["Escrever","Grafite","Borracha","Papel","Escola"]);
w("borracha","Objetos",["Apagar","Lapis","Erro","Branca","Escola"]);
w("apontador","Objetos",["Lapis","Pontar","Furo","Ponta","Escola"]);
w("mochila-escolar","Objetos",["Costas","Livros","Escola","Carregar","Material"]);
w("garrafa","Objetos",["Agua","Beber","Transportar","Plastico","Liquido"]);
w("bandeira","Objetos",["Pais","Simbolo","Haste","Cores","Nacao"]);
w("trofeu","Objetos",["Campeao","Vitoria","Premio","Ouro","Taca"]);
w("dinheiro","Objetos",["Notas","Moedas","Real","Pagamento","Carteira"]);
w("cadeado","Objetos",["Fechadura","Chave","Seguranca","Portao","Trancar"]);
w("abobora","Comidas",["Laranja","Grande","Halloween","Sopa","Doce"]);
w("chuchu","Comidas",["Verde","Legume","Leve","Refogado","Mole"]);
w("berinjela","Comidas",["Roxa","Comprida","Legume","Refogado","Salada"]);
w("mandioca","Comidas",["Raiz","Brasileira","Frita","Cozida","Farinha"]);
w("gengibre","Temperos",["Raiz","Picante","Cha","Tempero","Amarelo"]);
w("canela","Temperos",["Pau","Cheiroso","Doce","Tempero","Casca"]);
w("acafrao","Temperos",["Amarelo","Tempero","Arroz","Curcuma","Corante"]);
w("pimenta","Temperos",["Ardida","Pequena","Vermelha","Tempero","Picante"]);
w("mostarda","Temperos",["Amarela","Pasta","Tempero","Hot dog","Picante"]);
w("maionese","Temperos",["Branca","Pasta","Salada","Sanduiche","Oleo"]);
w("ketchup","Temperos",["Vermelho","Molho","Tomate","Batata frita","Doce"]);
w("vinagre","Temperos",["Acido","Salada","Tempero","Molinete","Conservar"]);
w("azeite","Temperos",["Verde","Oleo","Salada","Portugues","Saude"]);
w("oleo","Temperos",["Amarelo","Fritar","Gordura","Liquido","Cozinha"]);
w("farinha-trigo","Comidas",["Branca","Trigo","Massa","Pao","Cozinha"]);
w("fuba","Comidas",["Milho","Amarelo","Polenta","Bolo","Cozinha"]);
w("rabanada","Comidas",["Natal","Pao","Ovo","Frito","Acucar"]);
w("panetone","Comidas",["Natal","Frutas","Bolo","Italiano","Chocolate"]);
w("pernil","Comidas",["Carne","Porco","Assado","Natal","Cerdo"]);
w("lombo","Comidas",["Carne","Porco","Assado","Fatiado","Macio"]);
w("costela","Comidas",["Carne","Boi","Assada","Osso","Churrasco"]);
w("picanha","Comidas",["Carne","Boi","Gorda","Churrasco","Macia"]);
w("alcatra","Comidas",["Carne","Boi","Macia","Grelhada","Fina"]);
w("file-mignon","Comidas",["Carne","Macia","Alta","Grelhado","Corte nobre"]);
w("contra-file","Comidas",["Carne","Boi","Grelhado","Corte","Suculento"]);
w("linguica","Comidas",["Carne","Porco","Churrasco","Grelhada","Defumada"]);
w("pao-frances","Comidas",["Farinha","Casca dura","Mole dentro","Pequno","Trigo"]);
w("pao-integral","Comidas",["Trigo integral","Fibra","Saudavel","Escuro","Torrada"]);
w("croissant","Comidas",["Frances","Folhado","Manteiga","Cafe","Tipo de pao"]);
w("baguete","Comidas",["Frances","Comprida","Casca dura","Tradicional","Trigo"]);
w("brioche","Comidas",["Manteiga","Doce","Folhado","Frances","Macia"]);
w("cookie","Comidas",["Doce","Redondo","Gotas de chocolate","Crocante","Lanche"]);
w("donut","Comidas",["Redondo","Furo","Doce","Cobertura","Frito"]);
w("brownie","Comidas",["Chocolate","Quadradinho","Doce","Massa","Americano"]);
w("pudim","Comidas",["Doce","Leite","Calda","Caramelo","Sobremesa"]);
w("mousse","Comidas",["Chocolate","Leve","Cremoso","Doce","Sobremesa"]);
w("pave","Comidas",["Camadas","Biscoito","Creme","Sobremesa","Gelado"]);
w("sorvete","Comidas ja registrado",["Gelado","Doce","Sabores","Casquinha","Calor"]);
w("bolo","Comidas ja registrado",["Sobremesa","Forneado","Cobertura","Aniversario","Massa"]);
w("pizza","Comidas ja registrada",["Redonda","Massa","Queijo","Molho","Varios sabores"]);
w("hamburguer","Comidas ja registrado",["Sanduiche","Carne","Batata","Fast food","Queijo"]);
w("cachorro-quente","Comidas",["Salsicha","Pao","Mostarda","Ketchup","Lanche"]);
w("agulha","Objetos",["Costurar","Fina","Ponta","Linha","Pequena"]);
w("botao","Objetos",["Redondo","Costurar","Roupa","Furar","Prender"]);
w("ziper","Objetos",["Fecho","Roupa","Dentes","Abrir","Fechar"]);
w("alcool","Objetos",["Liquido","Limpeza","Higiene","70","Assptico"]);
w("desinfetante","Objetos",["Limpeza","Chao","Cheiroso","Liquido","Bacterias"]);
w("sabonete","Objetos",["Higiene","Banho","Cheiroso","Pessoa","Limpeza"]);
w("shampoo","Objetos",["Cabelo","Higiene","Lavar","Banho","Cuide"]);
w("condicionador","Objetos",["Cabelo","Macio","Pos shampoo","Higiene","Tratamento"]);
w("creme-dental","Objetos",["Dentes","Escovar","Pasta","Higiene","Limpeza"]);
w("fio-dental","Objetos",["Dentes","Limpeza","Fino","Higiene","Entre dentes"]);
w("enxaguante","Objetos",["Bocal","Dentes","Higiene","Liquido","Limpeza"]);
w("desodorante","Objetos",["Axilas","Higiene","Cheiro","Suor","Frescor"]);
w("perfume","Objetos",["Cheiro","Fragncia","Borrrifar","Elegante","Frasco"]);
w("hidratante","Objetos",["Pele","Creme","Higiene","Maciez","Corpo"]);
w("protetor-solar","Objetos",["Sol","Pele","Protecao","Praia","FPS"]);
w("repelente","Objetos",["Insetos","Mosquito","Protecao","Pele","Dengue"]);
w("inseticida","Objetos",["Insetos","Spray","Matar","Mosquito","Veneno"]);
w("veneno","Objetos",["Perigo","Cobra","Escorpiao","Txico","Mata"]);
w("antídoto","Objetos",["Veneno","Cura","Remedio","Salva","Reverso"]);
w("remedio","Objetos",["Comprimido","Doena","Cura","Farmacia","Saude"]);
w("xarope","Objetos",["Liquido","Tosse","Doena","Remedio","Garganta"]);
w("gotas","Objetos",["Liquido","Remedio","Olho","Nariz","Frasco"]);
w("injeção","Objetos",["Agulha","Seringa","Vaccina","Medicamento","Dor"]);
w("vacina","Objetos",["Doena","Preveno","Injecao","Imunidade","Saude"]);
w("curativo","Objetos",["Ferida","Protecao","Adesivo","Band-aid","Limpeza"]);
w("gaze","Objetos",["Ferida","Algodao","Limpeza","Hospital","Enrolar"]);
w("atadura","Objetos",["Enrolar","Ferida","Protecao","Hospital","Gaze"]);
w("esparadrapo","Objetos",["Adesivo","Fixo","Hospital","Curativo","Fita"]);
w("seringa","Objetos",["Agulha","Injecao","Medicamento","Hospital","Liquido"]);
w("termometro","Objetos",["Febre","Temperatura","Medir","Saude","Doena"]);
w("estetoscopio","Objetos",["Medico","Ouvir","Corpo","Corao","Batimentos"]);
w("macaco-ferramenta","Objetos",["Ferramenta","Levantar","Carro","Peso","Mecanica"]);
w("parafuso","Objetos",["Rosca","Fixo","Ferragem","Apertar","Metal"]);
w("porca","Objetos",["Rosca","Parafuso","Fixo","Ferragem","Apertar"]);
w("prego","Objetos",["Martelo","Fixo","Ferragem","Ponta","Madeira"]);
w("arruela","Objetos",["Redonda","Furo","Parafuso","Ferragem","Fixo"]);
w("broca","Objetos",["Furar","Ferragem","Ferramenta","Ponta","Parafuso"]);
w("furadeira","Objetos",["Furar","Parede","Ferramenta","Eletrica","Broca"]);
w("lixa","Objetos",["Raspar","Parede","Ferramenta","Grosa","Acabamento"]);
w("trena","Objetos",["Medir","Fita","Metal","Construcao","Fita metrica"]);
w("nivel","Objetos",["Nivelar","Bolha","Construcao","Preciso","Ferramenta"]);
w("betoneira","Objetos",["Concreto","Cimento","Construcao","Obra","Misturar"]);
w("andaime","Objetos",["Construcao","Altura","Tubo","Plataforma","Obra"]);
w("capacete","Objetos",["Protecao","Cabeca","Obra","Ciclismo","Seguranca"]);
w("epi","Objetos",["Seguranca","Trabalho","Protecao","Equipamento","Obra"]);
w("luva-de-obra","Objetos",["Protecao","Maos","Trabalho","Seguranca","Couro"]);
w("oculos-protecao","Objetos",["Olhos","Protecao","Trabalho","Obra","Seguranca"]);
w("mascara","Objetos",["Protecao","Respirar","Poeira","Vrus","Cirurgica"]);
w("avental","Objetos",["Protecao","Roupa","Cozinha","Trabalho","Limpeza"]);
w("jaleco","Objetos",["Branco","Medico","Laboratorio","Uniforme","Saude"]);
w("quadro","Objetos",["Pintura","Parede","Arte","Moldura","Tela"]);
w("escultura","Objetos",["Arte","Pedra","Marmore","Forma","Tridimensional"]);
w("estatua","Objetos",["Arte","Pessoa","Pedra","Publica","Homenagem"]);
w("busto","Objetos",["Cabeca","Ombro","Escultura","Homenagem","Arte"]);
w("relevo","Objetos",["Alto","Baixo","Escultura","Parede","Textura"]);
w("mosaico","Objetos",["Pequenos","Colorido","Arte","Parede","Azulejo"]);
w("vitral","Objetos",["Vidro","Colorido","Igreja","Janela","Arte"]);
w("azulejo","Objetos",["Quadrados","Parede","Cor","Cozinha","Banheiro"]);
w("ceramica","Objetos",["Barro","Forno","Vaso","Prato","Artesanato"]);
w("argila","Objetos",["Barro","Modelar","Ceramica","Escultura","Mole"]);
w("gesso","Objetos",["Branco","Parede","Escultura","Moldar","Fino"]);
w("cimento","Objetos",["Cinza","Construcao","Obra","Areia","Mistura"]);
w("areia","Natureza",["Fina","Praia","Construcao","Graos","Amarela"]);
w("cascalho","Natureza",["Pedra","Pequena","Construcao","Estrada","Drenagem"]);
w("pedra","Natureza",["Dura","Grande","Natureza","Montanha","Rocha"]);
w("rocha","Natureza",["Grande","Pedra","Montanha","Forte","Natureza"]);
w("mineral","Natureza",["Cristal","Pedra","Recurso","Natura","Terra"]);
w("cristal","Natureza",["Transparente","Brilha","Geometria","Pedra","Luxo"]);
w("diamante","Natureza",["Brilha","Duro","Joia","Tesouro","Pedra preciosa"]);
w("ouro","Natureza",["Metal","Amarelo","Joia","Valioso","Tesouro"]);
w("prata","Natureza",["Metal","Branco","Joia","Brillante","Talheres"]);
w("bronze","Natureza",["Metal","Marrom","Medalha","Escultura","Liga"]);
w("ferro-metal","Natureza",["Metal","Cinza","Forte","Ferrugem","Construcao"]);
w("aco","Natureza",["Metal","Forte","Resistente","Liga","Construcao"]);
w("aluminio","Natureza",["Metal","Leve","Prata","Latinha","Reciclavel"]);
w("cobre","Natureza",["Metal","Laranja","Fio","Eletrico","Moeda"]);
w("chumbo","Natureza",["Metal","Pesado","Cinza","Bateria","Toxico"]);
w("estanho","Natureza",["Metal","Prata","Mole","Solda","Lata"]);
w("latao","Natureza",["Metal","Amarelo","Liga","Cobre","Zinco"]);
w("madeira","Natureza",["Arvore","Marrom","Movel","Construcao","Material"]);
w("papel","Natureza",["Arvore","Folha","Escrita","Reciclavel","Branco"]);
w("borracha-material","Natureza",["Arvore","Elastico","Pneu","Borracha","Flexivel"]);
w("plastico","Natureza",["Petroleo","Sintetico","Leve","Moldavel","Reciclavel"]);
w("vidro","Natureza",["Transparente","Fragil","Areia","Reciclavel","Janela"]);
w("tecido","Natureza",["Algodao","Roupa","Fibra","Linho","Seda"]);
w("couro","Natureza",["Animal","Sapato","Bolsa","Resistente","Cinto"]);
w("algodao","Natureza",["Fibra","Roupa","Natural","Branco","Fofo"]);
w("la","Natureza",["Ovelha","Fibra","Cachecol","Frio","Natural"]);
w("seda","Natureza",["Fina","Brilhante","Roupa","Luxo","Natural"]);
w("poliester","Natureza",["Tecido","Sintetico","Resistente","Roupa","Fibra"]);
w("nylon","Natureza",["Sintetico","Resistente","Fio","Tecido","Corda"]);
w("corda","Objetos",["Grossa","Fina","Amarrar","Puxar","Nó"]);
w("barbante","Objetos",["Fino","Amarrar","Corda","Festa","Pacote"]);
w("linha","Objetos",["Fina","Costurar","Pesca","Carretel","Novelo"]);
w("novelo","Objetos",["Linha","La","Bola","Tricô","Circular"]);
w("la-de-tricô","Objetos",["Tricô","Cachecol","Fio","Agora","Agulha"]);
w("agulha-tricô","Objetos",["Tricô","Comprida","Ponta","La","Fazer"]);
w("tear","Objetos",["Tecido","Manual","Artesanato","Linhas","Antigo"]);
w("roca","Objetos",["Fiar","Linha","Antigo","Roda","Algodão"]);
w("fuso","Objetos",["Fiar","Roda","Linha","Antigo","Manual"]);
w("alfaiate","Profissões",["Roupa","Costurar","Sob medida","Terno","Tesoura"]);
w("costureira","Profissões",["Roupa","Maquina","Costurar","Tecido","Linha"]);
w("modista","Profissões",["Moda","Roupa","Criar","Vestido","Boutique"]);
w("estilista","Profissões",["Moda","Criar","Desfile","Roupa","Coleção"]);
w("modelo","Profissões",["Passarela","Fotos","Moda","Roupa","Beleza"]);
w("fotografo","Profissões",["Camera","Fotos","Imagem","Profissional","Clique"]);
w("cinegrafista","Profissões",["Camera","Filmar","Video","Evento","Movimento"]);
w("diretor-cinema","Profissões",["Filme","Cena","Atores","Roteiro","Camera"]);
w("roteirista","Profissões",["Roteiro","Historia","Filme","Escrever","Criar"]);
w("ator","Profissões",["Atuar","Novela","Filme","Teatro","Personagem"]);
w("atriz","Profissões",["Atuar","Filme","Novela","Teatro","Personagem"]);
w("dublador","Profissões",["Voz","Personagem","Animação","Filme","Gravar"]);
w("cantor","Profissões",["Musica","Voz","Show","Palco","Cancao"]);
w("musico","Profissões",["Instrumento","Musica","Banda","Orquestra","Apresentacao"]);
w("compositor","Profissões",["Criar","Musica","Letra","Cancao","Parititura"]);
w("maestro","Profissões",["Orquestra","Reger","Musica","Batuta","Concerto"]);
w("dancarino","Profissões",["Dançar","Palco","Ritmo","Coreografia","Ballet"]);
w("coreografo","Profissões",["Coreografia","Criar","Dança","Passos","Grupo"]);
w("pintor-artista","Profissões",["Tela","Pincel","Tinta","Arte","Quadro"]);
w("escultor","Profissões",["Escultura","Pedra","Marmore","Arte","Formas"]);
w("arquiteto","Profissões",["Projetar","Predio","Planta","Construcao","Espaco"]);
w("engenheiro","Profissões",["Obra","Calcular","Projetar","Construir","Exato"]);
w("pedreiro","Profissões",["Construir","Tijolo","Cimento","Parede","Obra"]);
w("eletricista","Profissões",["Fio","Luz","Tomada","Reparo","Eletrica"]);
w("encanador","Profissões",["Cano","Agua","Reparo","Pia","Vazamento"]);
w("mecanico","Profissões",["Carro","Motor","Ferramenta","Oficina","Reparo"]);
w("pintor-obra","Profissões",["Tinta","Parede","Pincel","Rolo","Casa"]);
w("carpinteiro","Profissões",["Madeira","Moveis","Serrote","Plaina","Marcenaria"]);
w("marceneiro","Profissões",["Madeira","Movel","Artesanato","Talhar","Acabamento"]);
w("vidraceiro","Profissões",["Vidro","Janela","Cortar","Colocar","Transparente"]);
w("serralheiro","Profissões",["Metal","Ferro","Portao","Solda","Ferramenta"]);
w("soldador","Profissões",["Solda","Metal","Unir","Fogo","Ferro"]);
w("torreiro","Profissões",["Torno","Metal","Peça","Precisao","Fabrica"]);
w("ferramenteiro","Profissões",["Ferramenta","Fabrica","Metal","Criar","Precisao"]);
w("ourives","Profissões",["Ouro","Joia","Fino","Detalhe","Luxo"]);
w("joalheiro","Profissões",["Joia","Criar","Ouro","Prata","Brilho"]);
w("relojoeiro","Profissões",["Relogio","Concerto","Pequeno","Precisao","Engrenagem"]);
w("boleiro","Profissões",["Bola","Futebol","Jogador","Campo","Gol"]);
w("professor","Profissões ja registrada",["Ensinar","Alunos","Escola","Aula","Educacao"]);
w("medico","Profissões ja registrada",["Doutor","Saude","Hospital","Remedio","Exame"]);
w("enfermeiro","Profissões",["Saude","Hospital","Cuidar","Paciente","Remedio"]);
w("dentista","Profissões",["Dente","Sorrir","Limpeza","Canal","Odonto"]);
w("veterinario","Profissões",["Animal","Saude","Clinica","Tratar","Bicho"]);
w("fisioterapeuta","Profissões",["Fisio","Movimento","Reabilitar","Corpo","Massagem"]);
w("nutricionista","Profissões",["Comida","Dieta","Saude","Alimentacao","Peso"]);
w("psicologo","Profissões",["Mente","Terapia","Conversar","Ajudar","Emocao"]);
w("psiquiatra","Profissões",["Mente","Medico","Remedio","Saude mental","Terapia"]);
w("farmaceutico","Profissões",["Remedio","Farmacia","Comprimido","Receita","Saude"]);
w("biologo","Profissões",["Vida","Natureza","Estudo","Laboratorio","Seres"]);
w("quimico","Profissões",["Laboratorio","Experimento","Elementos","Recacao","Ciencia"]);
w("fisico","Profissões",["Ciencia","Calculo","Teoria","Particula","Universo"]);
w("astronomo","Profissões",["Estrelas","Espao","Telescopio","Planeta","Universo"]);
w("astronauta","Profissões",["Espao","Foguete","Viajar","Lua","Gravidade"]);
w("piloto","Profissões",["Aviao","Voar","Aeronave","Cockpit","Comandante"]);
w("comissario","Profissões",["Aviao","Bordo","Voo","Seguranca","Cabine"]);
w("taxista","Profissões",["Taxi","Dirigir","Cidade","Passageiro","Corrida"]);
w("motorista","Profissões",["Dirigir","Transporte","Carro","Onibus","Volante"]);
w("caminhoneiro","Profissões",["Caminhao","Estrada","Carga","Viagem","Rodovia"]);
w("entregador","Profissões",["Entrega","Pedido","Moto","Aplicativo","Correr"]);
w("carteiro","Profissões",["Carta","Correio","Entregar","Selo","Uniforme"]);
w("jornalista","Profissões",["Noticia","Reportar","Jornal","Entrevista","Texto"]);
w("repórter","Profissões",["Noticia","Reportagem","Camera","Ao vivo","Entrevista"]);
w("editor","Profissões",["Texto","Revisar","Publicar","Livro","Jornal"]);
w("escritor","Profissões",["Livro","Historia","Texto","Publicar","Romance"]);
w("bibliotecario","Profissões",["Livro","Biblioteca","Organizar","Leitura","Silencio"]);
w("advogado","Profissões",["Lei","Justica","Tribunal","Processo","Cliente"]);
w("juiz","Profissões",["Justica","Lei","Tribunal","Sentenca","Julgamento"]);
w("promotor","Profissões",["Justica","Lei","Acusar","Tribunal","Processo"]);
w("policial","Profissões ja registrada",["Seguranca","Farda","Proteger","Lei","Patrulha"]);
w("bombeiro","Profissões",["Fogo","Resgatar","Emergencia","Caminhao","Mangueira"]);
w("segurança","Profissões",["Vigiar","Proteger","Portaria","Uniforme","Controle"]);
w("vigilante","Profissões",["Vigiar","Noturno","Seguranca","Ronda","Patrulha"]);
w("salva-vidas","Profissões",["Praia","Piscina","Resgatar","Afogamento","Apito"]);
w("mergulhador","Profissões",["Mergulho","Agua","Profundo","Cilindro","Mar"]);
w("pescador","Profissões",["Peixe","Pesca","Anzol","Mar","Vara"]);
w("agricultor","Profissões",["Plantar","Terra","Colheita","Fazenda","Comida"]);
w("fazendeiro","Profissões",["Fazenda","Gado","Plantacao","Campo","Criacao"]);
w("vaqueiro","Profissões",["Boi","Vaca","Sela","Boiada","Chapeu"]);
w("tratorista","Profissões",["Trator","Plantar","Terra","Maquina","Campo"]);
w("jardineiro","Profissões",["Jardim","Plantas","Flores","Podar","Cuidar"]);
w("paisagista","Profissões",["Jardim","Projeto","Plantas","Beleza","Natureza"]);
w("lenhador","Profissões",["Arvore","Machado","Cortar","Floresta","Toras"]);
w("mineiro","Profissões",["Mina","Carvão","Ferro","Escavar","Subterrâneo"]);
w("garimpeiro","Profissões",["Ouro","Pedra","Rio","Cascalho","Tesouro"]);
w("marinheiro","Profissões",["Navio","Mar","Uniforme","Barco","Capitão"]);
w("capitao-navio","Profissões",["Navio","Comandar","Timão","Mar","Oficial"]);
w("pesquisador","Profissões",["Pesquisa","Ciencia","Estudo","Laboratorio","Descobrir"]);
w("cientista","Profissões",["Pesquisa","Ciencia","Laboratorio","Teoria","Experimento"]);
w("matematico","Profissões",["Numeros","Calculo","Teoria","Exata","Resolver"]);
w("contador","Profissões",["Numero","Contabilidade","Financeiro","Imposto","Escritorio"]);
w("economista","Profissões",["Economia","Mercado","Dinheiro","Finança","Analise"]);
w("administrador","Profissões",["Gestao","Empresa","Liderar","Organizar","Decidir"]);
w("gerente","Profissões",["Liderar","Equipe","Empresa","Gestao","Responsavel"]);
w("diretor","Profissões",["Empresa","Chefia","Decidir","Liderar","Gestao"]);
w("presidente","Profissões",["Empresa","Chefiar","Decidir","Lider","Maior cargo"]);
w("ceo","Profissões",["Empresa","Lider","Decidir","Chefiar","Executivo"]);
w("empresario","Profissões",["Empresa","Negocio","Empreender","Patrao","Investir"]);
w("empreendedor","Profissões",["Inovar","Criar","Negocio","Iniciativa","Risco"]);
w("vendedor","Profissões",["Vender","Produto","Cliente","Loja","Comissao"]);
w("comerciante","Profissões",["Comercio","Loja","Vender","Produto","Negocio"]);
w("feirante","Profissões",["Feira","Vender","Barraca","Frutas","Publico"]);
w("padeiro","Profissões",["Pao","Forno","Padaria","Farinha","Cozinhar"]);
w("confeiteiro","Profissões",["Doce","Bolo","Confeitaria","Decorar","Chocolate"]);
w("churrasqueiro","Profissões",["Churrasco","Carne","Grelha","Assar","Fogo"]);
w("cozinheiro","Profissões",["Cozinhar","Comida","Fogao","Panelas","Restaurante"]);
w("chef","Profissões",["Cozinha","Comando","Restaurante","Criar","Cardapio"]);
w("garcom","Profissões",["Restaurante","Mesa","Servir","Pedido","Cliente"]);
w("bartender","Profissões",["Bebida","Bar","Coquetel","Drink","Atendente"]);
w("hoteleiro","Profissões",["Hotel","Hospede","Recepcao","Quarto","Turismo"]);
w("recepcionista","Profissões",["Atender","Cliente","Receber","Telefone","Agenda"]);
w("secretaria","Profissões",["Agenda","Organizar","Documento","Atender","Escritorio"]);
w("telefonista","Profissões",["Telefone","Ligar","Central","Atender","Ramal"]);
w("operador-callcenter","Profissões",["Telefone","Atender","Cliente","Central","Ajudar"]);
w("analista","Profissões",["Analisar","Dados","Relatorio","Sistema","Escritorio"]);
w("consultor","Profissões",["Consultar","Orientar","Empresa","Solucao","Especialista"]);
w("programador","Profissões ja registrada",["Computador","Codigo","Sistema","Programar","Logica"]);
w("desenvolvedor","Profissões",["Software","Programar","Web","Aplicativo","Sistema"]);
w("analista-sistemas","Profissões",["Sistema","Computador","Analisar","Projeto","TI"]);
w("designer","Profissões",["Criar","Visual","Arte","Design","Projeto"]);
w("web-designer","Profissões",["Site","Criar","Visual","Pagina","Internet"]);
w("ux-designer","Profissões",["Usuario","Experiencia","Interface","Facil","Teste"]);
w("product-manager","Profissões",["Produto","Gestao","Requisitos","Time","Roadmap"]);
w("project-manager","Profissões",["Projeto","Gestao","Prazo","Equipe","Entregar"]);
w("scrum-master","Profissões",["Agil","Time","Metodologia","Facilitar","Squads"]);
w("qa-tester","Profissões",["Testar","Qualidade","Bug","Software","Validar"]);
w("dba","Profissões",["Banco","Dados","SQL","Servidor","Informacao"]);
w("suporte-ti","Profissões",["Ajudar","Computador","Problema","Usuario","Solucionar"]);
w("redator","Profissões",["Texto","Escrever","Conteudo","Blog","Artigo"]);
w("copywriter","Profissões",["Texto","Vender","Anuncio","Persuasivo","Markenting"]);
w("marketeiro","Profissões",["Mercado","Divulgar","Vender","Propaganda","Estrategia"]);
w("publicitario","Profissões",["Propaganda","Anuncio","Criar","Midia","Marca"]);
w("relacoes-publicas","Profissões",["Comunicacao","Publico","Evento","Marca","Imagem"]);
w("analista-rh","Profissões",["Recursos humanos","Contratar","Entrevista","Funcionario","Folha"]);
w("estagiario","Profissões",["Aprender","Trabalho","Estagio","Jovem","Experiencia"]);
w("aprendiz","Profissões",["Aprender","Jovem","Ofcio","Profissão","Futuro"]);
w("voluntario","Profissões",["Ajudar","Doar","Tempo","Solidario","Causa"]);
w("missionario","Profissões",["Missao","Igreja","Ajudar","Longe","Fé"]);
w("religioso","Profissões",["Fé","Igreja","Crer","Deus","Oracao"]);
w("pároco","Profissões",["Padre","Igreja","Paróquia","Missas","Comunidade"]);
w("freira","Profissões",["Convento","Igreja","Habito","Religiosa","Voto"]);
w("monge","Profissões",["Mosteiro","Silencio","Oracao","Habito","Meditacao"]);
w("crianaca","Pessoas",["Pequena","Brincar","Infancia","Mae","Futuro"]);
w("bebe","Pessoas",["Pequeno","Recém-nascido","Choro","Mamar","Fralda"]);
w("adolescente","Pessoas",["Jovem","Fase","Crescimento","Escola","Mudanca"]);
w("adulto","Pessoas",["Crescido","Responsavel","Trabalho","Maduro","Maior idade"]);
w("idoso","Pessoas",["Velho","Idade","Sabedoria","Aposentado","Avos"]);
w("homem","Pessoas",["Masculino","Adulto","Pai","Marido","Crescado"]);
w("mulher","Pessoas",["Feminina","Mae","Adulto","Esposa","Senhora"]);
w("amigo","Pessoas",["Amizade","Leal","Parceiro","Proximo","Confiança"]);
w("inimigo","Pessoas",["Contra","Adversario","Rival","Oposição","Hostil"]);
w("vizinho","Pessoas",["Perto","Casa","Lado","Morar","Proximo"]);
w("irmao","Pessoas",["Familia","Mae","Pai","Parente","Proximo"]);
w("primo","Pessoas",["Familia","Tio","Parente","Proximo","Sangue"]);
w("tio","Pessoas",["Familia","Irma do pai","Parente","Proximo","Adulto"]);
w("sobrinho","Pessoas",["Familia","Filho do irmao","Parente","Proximo","Jovem"]);
w("avo","Pessoas",["Familia","Velhinho","Idoso","Sabedoria","Carinho"]);
w("neto","Pessoas",["Familia","Jovem","Pequno","Filho do filho","Futuro"]);
w("pai","Pessoas",["Familia","Progenitor","Paternidade","Chefe","Exemplo"]);
w("mae","Pessoas ja registrada",["Familia","Maternidade","Genitora","Cuidado","Amor"]);
w("crianca","Pessoas",["Pequna","Brincar","Infância","Inocencia","Escola"]);
w("genero","Pessoas",["Masculino","Feminino","Identidade","Diversidade","Igualdade"]);
w("heroi","Pessoas",["Coragem","Salvar","Poder","Força","Justica"]);
w("heroina","Pessoas",["Coragem","Salvar","Feminina","Força","Justica"]);
w("vilao","Pessoas",["Mal","Inimigo","Destruir","Poder","Contra"]);
w("capanga","Pessoas",["Ajudante","Vilao","Segurança","Bandido","Executor"]);
w("chefao","Pessoas",["Lider","Crime","Mafia","Comandar","Poder"]);
w("refem","Pessoas",["Capturado","Preso","Perigo","Socorro","Resgate"]);
w("vitima","Pessoas",["Sofrer","Crime","Acidente","Lesado","Perda"]);
w("sobrevivente","Pessoas",["Viver","Acidente","Resistir","Forte","Guerra"]);
w("bandido","Pessoas",["Crime","Roubar","Mal","Fugir","Policia"]);
w("ladrao","Pessoas",["Roubar","Furtar","Crime","Bandido","Cadeia"]);
w("assaltante","Pessoas",["Roubar","Violento","Crime","Perigo","Arma"]);
w("golpista","Pessoas",["Enganar","Fraude","Golpe","Mentira","Crime"]);
w("investigador","Pessoas",["Policia","Procurar","Pistas","Detetive","Solucionar"]);
w("detetive","Pessoas",["Investigacao","Pistas","Misterio","Solucionar","Crime"]);
w("espião","Pessoas",["Disfarcar","Segredo","Informacao","Agente","Governo"]);
w("agente-secreto","Pessoas",["Governo","Missao","Espionagem","Sigilo","Operacao"]);
w("soldado","Pessoas",["Exercito","Guerra","Farda","Arma","Defender"]);
w("guerreiro","Pessoas",["Lutar","Forca","Batalha","Espada","Bravo"]);
w("gigante","Fantasia",["Grande","Forca","Monstro","Altura","Assustador"]);
w("elfo","Fantasia",["Orelhas pontudas","Magia","Arco","Floresta","Imortal"]);
w("anao","Fantasia",["Pequeno","Barba","Machado","Mina","Ferreiro"]);
w("fada","Fantasia",["Magia","Asas","Pequena","Brilha","Encantar"]);
w("bruxa","Fantasia",["Magia","Vassoura","Caldron","Sombrio","Poder"]);
w("mago","Fantasia",["Magia","Varinha","Poder","Feitico","Sabedoria"]);
w("feiticeiro","Fantasia",["Magia","Poder","Feitico","Sombrio","Misterioso"]);
w("ogro","Fantasia",["Grande","Feio","Forca","Monstro","Burro"]);
w("troll","Fantasia",["Ponte","Grande","Feio","Pedra","Forca"]);
w("orque","Fantasia",["Verde","Guerra","Forca","Monstro","Mal"]);
w("goblin","Fantasia",["Pequeno","Verde","Mal","Criatura","Furtivo"]);
w("esqueleto","Fantasia",["Osso","Morto","Assombracao","Caveira","Sem carne"]);
w("zumbi","Fantasia",["Morto-vivo","Andar","Devagar","Infectado","Apocalipse"]);
w("fantasma","Fantasia ja registrado",["Assombracao","Transparente","Alma","Assustar","Flutuar"]);
w("vampiro","Fantasia",["Sangue","Noite","Morcego","Imortal","Conde"]);
w("lobisomem","Fantasia",["Lobo","Homem","Lua cheia","Transformar","Uivar"]);
w("mumia","Fantasia",["Antigo","Egito","Enfaixado","Sarcófago","Morto-vivo"]);
w("ciclope","Fantasia",["Olho so","Grande","Grego","Monstro","Forca"]);
w("minotauro","Fantasia",["Touro","Homem","Labirinto","Grego","Monstro"]);
w("centauro","Fantasia",["Homem","Cavalo","Grego","Arco","Metade"]);
w("sereia","Fantasia",["Peixe","Mulher","Mar","Canto","Encantar"]);
w("unicornio","Fantasia",["Cavalo","Chifre","Magico","Branco","Pureza"]);
w("dragao","Fantasia",["Fogo","Asas","Grande","Escama","Voa"]);
w("grifo","Fantasia",["Leao","Aguia","Asas","Mitologia","Forca"]);
w("fênix","Fantasia",["Fogo","Renascer","Passaro","Imortal","Cinzas"]);
w("quimera","Fantasia",["Leao","Cabra","Serpente","Monstro","Mitologia"]);
w("harpia","Fantasia",["Mulher","Passaro","Asas","Mitologia","Monstro"]);
w("medusa","Fantasia",["Serpentes","Cabelo","Olhar","Pedra","Grega"]);
w("basilisco","Fantasia",["Cobra","Rei","Olhar","Morte","Mitologia"]);
w("hidra","Fantasia",["Cabecas","Cortar","Multiplas","Serpente","Mitologia"]);
w("kraken","Fantasia",["Polvo","Gigante","Mar","Lula","Monstro"]);
w("leviata","Fantasia",["Mar","Monstro","Grande","Bilia","Serpente"]);
w("behemoth","Fantasia",["Terra","Grande","Bíblia","Monstro","Poder"]);
w("cerberus","Fantasia",["Tres cabecas","Cachorro","Guardiao","Inferno","Grego"]);
w("pégaso","Fantasia",["Cavalo","Asas","Grego","Voar","Branco"]);
w("fênix","Fantasia",["Fogo","Renascimento","Passaro","Eterno","Cinzas"]);
w("ariete","Guerra",["Arma","Bater","Porta","Antiga","Muralha"]);
w("escudo","Guerra ja registrado",["Proteger","Guerreiro","Defesa","Batalha","Braco"]);
w("espada","Guerra ja registrada",["Arma","Guerreiro","Fio","Luta","Bainha"]);
w("arco-flecha","Guerra",["Arma","Atirar","Flexa","Alvo","Precisao"]);
w("lança","Guerra",["Arma","Longa","Ponta","Guerreiro","Atirar"]);
w("cimitarra","Guerra",["Espada","Curva","Oriental","Guerreiro","Fio"]);
w("katana","Guerra",["Espada","Japonesa","Samurai","Fio","Curva"]);
w("canca","Guerra",["Arma","Corrente","Bolas","Pesar","Golpe"]);
w("clava","Guerra",["Arma","Pau","Ponta","Pesar","Antiga"]);
w("machado-guerra","Guerra",["Arma","Guerreiro","Cortar","Laminas","Pesar"]);
w("martelo-guerra","Guerra",["Arma","Pesar","Esmagar","Guerreiro","Ferro"]);
w("alabarda","Guerra",["Arma","Lanca","Machado","Longa","Ponta"]);
w("espingarda","Guerra",["Arma","Fogo","Tiros","Municao","Canos"]);
w("revover","Guerra",["Arma","Revolver","Tiros","Curta","Municao"]);
w("canhao","Guerra",["Arma","Bala","Explosao","Grande","Exercito"]);
w("tanque-guerra","Guerra",["Armadura","Lagartas","Canhao","Exercito","Pesar"]);
w("bomba","Guerra",["Explosao","Destruir","Poder","Militar","Perigo"]);
w("granada","Guerra",["Explosao","Jogar","Militar","Pequena","Morte"]);
w("mina-terrestre","Guerra",["Explosao","Pisar","Militar","Perigo","Campo"]);
w("fortaleza","Guerra",["Forte","Muralha","Defesa","Proteger","Castelo"]);
w("guerra","Guerra",["Conflito","Batalha","Exercitos","Paises","Lutar"]);
w("batalha","Guerra",["Luta","Guerra","Exrcito","Confronto","Campo"]);
w("trégua","Guerra",["Pausa","Paz","Parar","Guerra","Acordo"]);
w("paz","Guerra",["Calma","Tranquilidade","Harmonia","Guerra","Uniao"]);
w("aliança","Guerra",["Uniao","Paises","Juntos","Acordo","Apoio"]);
w("tratado","Guerra",["Acordo","Paises","Lei","Paz","Assinar"]);
w("bandeira-guerra","Guerra",["Bandeira","Exercito","Simbolo","Nacao","Marcha"]);
w("tropa","Guerra",["Soldados","Grupo","Exercito","Unidade","Militares"]);
w("combatente","Guerra",["Lutar","Soldado","Guerrilha","Batalha","Frente"]);
w("casco","Animais",["Tartaruga","Protecao","Duro","Costas","Carrega"]);
w("patas","Animais",["Animais","Pes","Garras","Andar","Pegada"]);
w("focinho","Animais",["Animais","Nariz","Frente","Cheirar","Cara"]);
w("cauda","Animais",["Animais","Rabinho","Traseira","Balançar","Peluda"]);
w("asa","Animais",["Passaro","Voar","Pluma","Ceu","Aves"]);
w("pena-pássaro","Animais",["Ave","Leve","Colorida","Voar","Cobrir"]);
w("bico","Animais",["Passarinho","Comer","Bicar","Fino","Ave"]);
w("ninho","Animais",["Passaro","Ovos","Arvore","Casa","Filhotes"]);
w("chifre","Animais",["Touro","Vaca","Cabeça","Ponta","Defesa"]);
w("juba","Animais",["Leao","Pelos","Cabeça","Rei","Selvagem"]);
w("pelo","Animais",["Animal","Pelagem","Corpo","Macio","Peludo"]);
w("escama","Animais",["Peixe","Reptil","Corpo","Dura","Protecao"]);
w("caracol","Animais",["Concha","Devagar","Lesma","Espiral","Rastro"]);
w("lesma","Animais",["Devagar","Mole","Rastro","Horta","Praga"]);
w("minhoca","Animais",["Fina","Comprida","Terra","Bicho","Furo"]);
w("tatu","Animais ja registrado",["Armadura","Enrolar","Brasileiro","Cavoucar","Carapaca"]);
w("capivara","Animais",["Roedor","Grande","Agua","Brasileiro","Calmo"]);
w("preguica","Animais",["Devagar","Arvore","Bicho-preguica","Instalao","Fofinha"]);
w("canguru","Animais",["Saltar","Bolsa","Australia","Grande","Mamifero"]);
w("coala","Animais",["Eucalipto","Arvore","Australia","Fofinho","Mamifero"]);
w("ornitorrinco","Animais",["Bico","Pata","Mamifero","Ovo","Australia"]);
w("tamandua","Animais",["Formiga","Lingua","Comprida","Brasil","Mamifero"]);
w("ratinho","Animais",["Pequeno","Rato","Roedor","Fofinho","Veloz"]);
w("hamster","Animais",["Pequeno","Bolinha","Fofinho","Gaiola","Rato"]);
w("porquinho-da-india","Animais",["Pequno","Fofinho","Roedor","Gaiola","Rato"]);
w("chinchila","Animais",["Peluda","Fofinha","Pequena","Cinza","Roedor"]);
w("coelhinho","Animais",["Pequeno","Fofo","Orelhudo","Ovo de pascoa","Pula"]);
w("raposa","Animais ja registrada",["Vermelha","Astuta","Selvagem","Rabo peludo","Raposa"]);
w("urso-polar","Animais",["Branco","Gelado","Urso","Polo Norte","Grande"]);
w("urso-pardo","Animais",["Grande","Peludo","Floresta","Selvagem","Poderoso"]);
w("urso-negro","Animais ja registrado",["Floresta","Preto","Grande","Perigo","Onivoro"]);
w("leao-marinho","Animais",["Mar","Foca","Grande","Juba","Acrobata"]);
w("foca","Animais ja registrada",["Mar","Bola","Nariz","Gorda","Mamifero marinho"]);
w("golfinho","Animais ja registrado",["Mar","Inteligente","Saltar","Mamifero","Brincalhao"]);
w("baleia","Animais ja registrada",["Mar","Gigante","Jato","Mamifero","Oceano"]);
w("tubarao","Animais ja registrado",["Mar","Dentes","Perigo","Predador","Barbatana"]);
w("lula","Animais",["Mar","Tentaculos","Oito","Cabeça","Calmar"]);
w("polvo","Animais ja registrado",["Oito tentaculos","Mar","Inteligente","Ventosas","Moluco"]);
w("caranguejo","Animais",["Casca","Pinça","Andar de lado","Praia","Mar"]);
w("siri","Animais",["Casca","Pinça","Praia","Mar","Andar de lado"]);
w("lagosta","Animais",["Mar","Vermelha","Pinça","Crustáceo","Valiosa"]);
w("camarao","Animais",["Mar","Pequeno","Rosa","Crustaceo","Camarão"]);
w("ostra","Animais",["Mar","Concha","Perola","Moluco","Fechada"]);
w("mexilhao","Animais",["Mar","Concha","Azul","Preto","Moluco"]);
w("estrela-do-mar","Animais",["Mar","Estrela","Bracos","Colorida","Fundodo mar"]);
w("cavalo-marinho","Animais",["Mar","Pequeno","Curioso","Cavalo","Macho gravida"]);
w("agua-viva","Animais",["Mar","Transparente","Gel","Queimadura","Tentaculos"]);
w("coral","Animais",["Mar","Colorido","Recife","Duro","Ecossistema"]);
w("alga","Natureza",["Mar","Verde","Fotossíntese","Vegetal","Aquatica"]);
w("plâncton","Natureza",["Microscopico","Mar","Flutuar","Cadeia","Microbios"]);
w("beija-flor","Animais",["Pequeno","Voa rapido","Flor","Néctar","Asas rapidas"]);
w("pavão","Animais",["Colorido","Cauda grande","Ave","Abrir leque","Azul"]);
w("cisne","Animais",["Branco","Pescoço longo","Lago","Elegante","Ave"]);
w("pato","Animais ja registrado",["Agua","Bico","Pata","Quack","Mergulhar"]);
w("galinha","Animais ja registrada",["Ovo","Pintinho","Quintal","Cocó","Granja"]);
w("galo","Animais ja registrado",["Crista","Cantar","Cocoricó","Amanhecer","Granja"]);
w("pintinho","Animais",["Amarelinho","Pequeno","Galinha","Ovo","Cute"]);
w("peru","Animais",["Grande","Natal","Glu glu","Penas","Cauda"]);
w("avestruz","Animais",["Grande","Corre rapido","Asa pequena","Cabeça pequena","Pescoço longo"]);
w("ema","Animais",["Grande","Ave brasileira","Corre","Cerrado","Asa pequena"]);
w("pinguim","Animais ja registrado",["Frio","Antartica","Fraque","Nadar","Andar balancando"]);
w("gaivota","Animais",["Mar","Praia","Voa","Branca","Cinza"]);
w("pelicano","Animais",["Bico grande","Bolsa","Peixe","Praia","Mar"]);
w("flamingo","Animais",["Rosa","Uma perna","Pescoço longo","Lago","Ave elegante"]);
w("tucano","Animais ja registrado",["Bico grande","Colorido","Floresta","Amazônia","Fruta"]);
w("papagaio","Animais ja registrado",["Fala","Cores","Brasileiro","Repete","Verde"]);
w("arara","Animais ja registrada",["Azul","Vermelha","Colorida","Grande","Brasileira"]);
w("bola-brinquedo","Brinquedos",["Bola","Pular","Crianca","Brincar","Colorida"]);
w("boneca","Brinquedos",["Boneca","Menina","Brincar","Vestir","Cuidar"]);
w("carrinho","Brinquedos",["Carro","Pequeno","Brincar","Crianca","Rodas"]);
w("robo-brinquedo","Brinquedos",["Robô","Brincar","Eletronico","Movimento","Pilha"]);
w("quebra-cabeca","Brinquedos",["Montar","Peças","Imagem","Desafio","Completar"]);
w("dominó","Brinquedos",["Peças","Numeros","Juntar","Pontinhos","Jogo"]);
w("dado","Brinquedos",["Jogar","Numeros","Cubo","Sorte","Aleatorio"]);
w("pião","Brinquedos",["Girar","Ponta","Brincar","Colorido","Bambalalão"]);
w("bola-de-gude","Brinquedos",["Gude","Pequena","Vidro","Colorida","Jogo"]);
w("pipoca","Comidas",["Milho","Panela","Sal","Cinema","Estourar"]);
w("carne-seca","Comidas",["Carne","Seca","Sol","Nordeste","Charque"]);
w("feijoada","Comidas",["Feijão","Carne","Arroz","Brasileira","Festa"]);
w("farofa","Comidas",["Farinha","Brasileira","Churrasco","Manteiga","Acompanhamento"]);
w("acai","Comidas",["Roxo","Energia","Pará","Tigela","Frutas"]);
w("moqueca","Comidas",["Peixe","Leite de coco","Dende","Baiana","Capixaba"]);
w("churrasco","Comidas",["Carne","Grelhada","Fogo","Esqueto","Confraternizacao"]);
w("primavera","Natureza",["Flores","Estacao","Ano","Colorido","Sol"]);
w("verao","Natureza",["Calor","Sol","Praia","Ferias","Estacao"]);
w("outono","Natureza",["Folhas","Estacao","Vento","Frio","Marrom"]);
w("inverno","Natureza",["Frio","Neve","Casaco","Estacao","Geada"]);
w("lua-cheia","Natureza",["Lua","Noite","Redonda","Clara","Ce-u"]);
w("lua-nova","Natureza",["Lua","Escura","Noite","Quarto","Crescente"]);
w("sol","Natureza",["Estrela","Dia","Calor","Luz","Centro"]);
w("céu","Natureza",["Azul","Nuvens","Alto","Infinito","Aereo"]);
w("nuvem","Natureza ja registrada",["Branca","Ce-u","Chuva","Flutuar","Algoda"]);
w("estrela","Natureza ja registrada",["Brilha","Noite","Ce-u","Luz","Pequena"]);
w("planeta","Natureza",["Terra","Orbita","Sol","Redondo","Sistema"]);
w("mercurio","Natureza",["Planeta","Pequeno","Quente","Sol","Primeiro"]);
w("venus","Natureza",["Planeta","Brilha","Noite","Estrela d alva","Quente"]);
w("marte","Natureza",["Planeta","Vermelho","Segundo","Sol","Guerra"]);
w("jupiter","Natureza",["Planeta","Grande","Gasoso","Mana","Listrado"]);
w("saturno","Natureza",["Planeta","Anel","Gasoso","Bonito","Sol"]);
w("urano","Natureza",["Planeta","Azul","Gasoso","Segundo","Gelo"]);
w("netuno","Natureza",["Planeta","Azul escuro","Ventania","Gasoso","Ultimo"]);
w("sol","Natureza",["Sol","Estrela","Dia","Calor","Luz"]);
w("galáxia","Natureza",["Estrelas","Espaço","Via Lactea","Universo","Astronomia"]);
w("nebulosa","Natureza",["Gas","Poerira","Estrelas","Espaco","Colorida"]);
w("cometa","Natureza",["Gelo","Poerira","Cauda","Espaco","Rastro"]);
w("asteroide","Natureza",["Pedra","Espaco","Cinturao","Pequeno","Orbita"]);
w("meteoro","Natureza",["Estrela cadente","Brilha","Ce-u","Rastro","Passar"]);
w("buraco-negro","Natureza",["Gravidade","Invisible","Absorver","Espaco","Universo"]);
w("big-bang","Natureza",["Inicio","Universo","Explosao","Criacao","Teoria"]);
w("cosmo","Natureza",["Universo","Espaco","Infinito","Cosmico","Galaxias"]);
w("vidro-janela","Objetos",["Transparente","Janela","Quadro","Vidro","Fragil"]);
w("sino-porta","Objetos",["Tocar","Entrada","Porta","Som","Campainha"]);
w("campainha","Objetos",["Tocar","Entrada","Sino","Porta","Chamar"]);
w("telhado","Objetos",["Casa","Cobertura","Telha","Protecao","Sobre"]);
w("parede","Objetos",["Casa","Divisao","Tijolo","Quarto","Tinta"]);
w("porta","Objetos ja registrada",["Entrada","Sair","Casa","Abrir","Fechar"]);
w("janela","Objetos ja registrada",["Abrir","Ver","Luz","Vidro","Ar"]);
w("chave","Objetos ja registrada",["Abrir","Fechadura","Porta","Metal","Acesso"]);
w("escada","Objetos",["Subir","Degraus","Altura","Residencial","Casa"]);
w("corrimao","Objetos",["Segurar","Escada","Balaustre","Ajuda","Acessibilidade"]);
w("tijolo","Objetos",["Construcao","Parede","Cimento","Vermelho","Retangular"]);
w("piso","Objetos",["Chao","Revestimento","Casa","Ceramica","Andar"]);
w("lajota","Objetos",["Chão","Piso","Ceramica","Quadrado","Casa"]);
w("interruptor","Objetos",["Luz","Ligar","Desligar","Parede","Eletricidade"]);
w("tomada","Objetos",["Eletrica","Ligar","Fio","Parede","Tomar"]);
w("fio-eletrico","Objetos",["Eletricidade","Cobre","Corrente","Cabo","Energia"]);
w("motor","Objetos",["Maquina","Movimento","Forca","Rotacao","Energia"]);
w("hélice","Objetos",["Girar","Vento","Aviao","Navio","Propulsor"]);
w("peneira","Objetos",["Furos","Separar","Cozinha","Areia","Farinha"]);
w("ralador","Objetos",["Ralar","Queijo","Cozinha","Furos","Metal"]);
w("liquidificador","Objetos",["Bater","Liquido","Cozinha","Vitamina","Eletrico"]);
w("batedeira","Objetos",["Bater","Massa","Claras","Cozinha","Eletrica"]);
w("torradeira","Objetos",["Torrar","Pao","Cozinha","Eletrica","Café da manhã"]);
w("cafeteira","Objetos",["Cafe","Cozinha","Eletrica","Passar","Coador"]);
w("coador","Objetos",["Cafe","Passar","Filtro","Pano","Cozinha"]);
w("chaleira","Objetos",["Agua","Ferver","Cha","Cozinha","Bico"]);
w("panela-de-pressao","Objetos",["Cozinhar","Rapido","Pressao","Válvula","Panelas"]);
w("frigideira","Objetos",["Fritar","Panela","Fundo chato","Cozinha","Alca"]);
w("assadeira","Objetos",["Forno","Assar","Bolo","Cozinha","Retangular"]);
w("forma-bolo","Objetos",["Bolo","Forno","Redonda","Cozinha","Assar"]);
w("espátula","Objetos",["Virar","Cozinha","Frigideira","Pao","Instrumento"]);
w("pegador-macarrao","Objetos",["Macarrao","Cozinha","Pegar","Talher","Espaguete"]);
w("abridor-garrafa","Objetos",["Garrafa","Abrir","Tampa","Cozinha","Cerveja"]);
w("saca-rolhas","Objetos",["Vinho","Abrir","Rolha","Cozinha","Espiral"]);
w("régua","Objetos",["Medir","Reta","Escola","Centimetros","Precisao"]);
w("compasso","Objetos",["Desenhar","Circulo","Geometria","Escola","Régua"]);
w("transferidor","Objetos",["Angulo","Medir","Geometria","Escola","Grau"]);
w("esquadro","Objetos",["Angulo","Noventa","Geometria","Escola","Desenho"]);
})();
